# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsApi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsApi
  pod 'Kingfisher'
  pod 'Alamofire'
  

  target 'NewsApiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsApiUITests' do
    # Pods for testing
  end

end
